GLC:MKM0AwQqAiwBrMOV8mEzMNQ1g7nQaVPjlCQiXcTOH8Q/dsw=
GLC:Rw0pofUykeRG3J7/mSNKtCJy0VKvQVQIg97hVfIf5mtdHQjDd5AmeW6nM8X636Zi
GLC:BBtCVzKdTwhg1gzeRxzPtkPGujHTN+cww2jtS3U=
GLC:AZFROHzi4rs5pFDnlBNkc1cMylFgWPqKVCnsra1LQpGgMiteyPM=
GLC:0WrjFyLdQRlEbpjC4WDrLAQLmy2Y1U9UhaQDJTMoV0y/geYx8yBAv0xigjuygt8Q
GLC:9FRGOpC1VoAzchGWbO1s2nkTtt3vMQEf9taTGdzOKyw/EVQqIusOcQg2
GLC:O0Z6T6ql70SU/JVB1sAwNk+YWuvi1UMCTn2OVp8uMmCBS9ymfNKIcLhClNjnOOegBnqWE0YPUSWzhA==
GLC:rI9e5H/eAXzZCXvnvroZ/83lxCNHVySDvpfY5tK8P2hsMP95Uc9OPCcgqqCYsgpFv8Y=
GLC:bywJaWeu2vH5DhSt8u0zgcvG1vlGecGPpH9ahm5XJTx/66Mgf8RCLyDwoiD26L/vS5SOuAiRluhO3yGLFfzlsLR7
GLC:ADXhOvJHZg8/wOtCddrjui92fUYmo9WcHB4uP6Nmpr8pkde83+aF+M6JillM24+1/4GVLA==
GLC:TzSKvv+7ZXTrgHjB75s+M1PDgRh0iNAK0GUAu+dbzkYzzJadjdrJR3pHS5cffUEEhNY/CTyFlgt/jP0tJV/G9xz3Vgp036RW0ZsIUg==
GLC:BBtCVzKdTwhg1gzeRxzPtkPGujHTN+cww2jtS3U=
GLC:T285/rU9isb2zct1yqVgkvzgF8UOg9YkE16VLDIXLd4arWDDODM=
GLC:NaUxWVHXgFtfhj8F0AObFaAd+EdDL7pASOAFm3WyqIcZU+la2lfBpOgL+JwDzeffwj8=
GLC:rWnDXcl7IhZLpMIdZCIXhl2QJSIhQZcGeJD1j/idkcxdvqE+HVsUa6eiYAwpHKIGR8Y=
GLC:dVDuTy/sHMJyttU3lVem8peEHpA8QKSp9eopNPQZptycUeqxY3vN979VD50b4BzZsrkclZprO9ce
GLC:Xml2s9z3/whtYbd7+CXeFGM6DI0wtA5N1ie/C0IBay3ZDgBvHJcwCKJKVVoSAQNpNhIqdw==
GLC:wUew104jti0qmRKAvN5tfukMXNoTJic/I1j+Mgjr5x6dtlHSJBWtlFpBp6kgh3EPTAfK73StrY1hgHFd
GLC:KpZIuo5px/urVmvsCV54Dj1XO8eomLOuzeGwuXHbDo33X9v70BVFC7uQ9rgvORz+D/72l6waXk5zwFdPGU3fqVCu3RI=
GLC:mZUh6nPWyVXeXrRDPzYnl4jP5qV+MmzkJnjkysp20tnJsJLkvETGTyFHzS9fm62CDViubbT23GVYpCU4boRw/RMBfPi/KPA=
GLC:BBtCVzKdTwhg1gzeRxzPtkPGujHTN+cww2jtS3U=
GLC:BcHH9487Q+tBNx1TxLiFZM4BUUVFZhDZY+Y7wrCUKa7njq9vg58=
GLC:HqoOWLh4DdUMN9pnETpSuPd13AQcpSDCibGo6gjaLXfmtcC+dTp1nkN5PwSOtqQVVTP6EOFfng8bUjOL
GLC:PlEONhlMCT+8vYwRN3ibyesDRqY+I632wOUws1TT44f8MUTg6OmMrUZUJYwS0oInalQyMg==
GLC:VNriNnIDEdRZhnVJmIZkap4tMOoOOadBlvJsiYafihfPOraVEYGY3n7Uqq40toXjr7VE/zTMn4vqhn8/eHGrF4a7Kt+h9ecyMxq5yyS35VWXU/XfwQ==
GLC:qLOBRC0ex+CGzFKTJO4+AEvo5Ans7Xl1DaW9TNBlcTot9I+nJxtMmbAmkFxk6/oppvrG4524uQpVvUio
GLC:m8xguyJriAI75MiYD0Y0H1RtYGCoSlAkWm9p0heIX2thxKEiaBvvTaisNTn5BSKZ1shHaIzd94y4b/nVPHtYWfcloaRnIw==
GLC:0hlNyGktvBF31fQRmA+gMOV2MihlxvEcK68mIgVoJSeU54oyEGtFFO3e7OoRk791fJQu4vIdCboW08PHLd8Yrg==
GLC:YD5CHYMWm9M0/HK2ojjytU4vulVvGDeC4MNhRGM7ev1UPnnf8IMUOf9uk4UT0tYxXdq99lMFUYLbGt06xwOnj3kaCTywZgWu6zGmPdrnqQNtKMpps12Ili5jhis2
GLC:BBtCVzKdTwhg1gzeRxzPtkPGujHTN+cww2jtS3U=
GLC:eZgnqiFe3HHaholanUiJ2Tqaq/5l9WUw3xxeVKFScO7+56cET9c=
GLC:zWhgvwlgXYY7T/9sXhRsvNVdhmzDeqhr3+GpfoY72iu1z1CJ6Kb10+nmLrIxvF64V70=
GLC:6qQi9kBkcgIXK7fs4ZTr5wUtGT1SDFgjwCzpdxqXNGCWxt5E65/BLTm4k4EA
GLC:80MBXDg6y/BOFOuEbHhxbd/gU5LxbGho1YmfoE96gk17dkQYtTadgnC3yswamsW+EKhXUkiKSRdaXj+YnCVmMD+eBv78
GLC:kmi/SKQRdyWkvLDQIYkQz8sLJ/WqtgDcG84KndPtr+emFqyffzeIznjNUvE/aPlX+/o=
GLC:8QSBV5NKoTUMlokXIgURUaoe5+73hLtpNUfRrw9mn2KLnsLeSq43e6W1fy3PM3RluSMfVok8L9g2kaKd
GLC:GZrf4Ve7lL3kX5nnrU4k95FJk4VG0z7oePyqD96DLpyncT0ULHeuEm1WK+esBYtuWCXmx1rEve7y
GLC:x45ftTkWt4EdsEp2ska2sqdvv7LGsX7L6TGWDvhXn8kZPSK9ZAEcFBeyeVpbwdbLjpwQtlj45IhBuaVKPu5oT0D/Fa5RO4ap8FYFkLkElDtcp+c=
GLC:BBtCVzKdTwhg1gzeRxzPtkPGujHTN+cww2jtS3U=
GLC:faqrC8PECyugGNLV+GsT9KtkNfy11XdwO+kfGFlr25aIYqI/sj4=
GLC:maSrYgJBLNFRLQPvSnjsuBFWo9jT5kiXrYPxZb91GmS0E1Ftwq2GruX314O35E4t6B+W
GLC:Y5tOALcyALaSjV6JsicQD2t6m7syya8AwgMV8AtlOvMTJVb4HzUS9VaA40wTcg==
GLC:zj2p2EqxpgBTx7Tbr/uQvRV7xm5V0rZbYFX8ykmKzXMfTs4Q865wVDbPTitgCYlBaP0CxJsKvdXWOOd6qANZTbcN7bE=
GLC:DGBpZ5Tqw6yOwEa4l7bRvuchZg+wc2yjgRzcjOgS3Vh9MQHFhzwCN5FOBFF27LN15Q==
GLC:K4ksOAGg2s1hT5qckM8eLrVorRGcZzC3S2vkqkGW6oqQvHYXltxMDhrl4CuEAuO+mj6zUxQS89n+XGT40w==
GLC:PuIY46zNHigxAusgooFMBP6lbXJJwuxksq5G96nRj5Ws8J+9k0GHbkr61vxMxMaxNR/TlVhHrg==
GLC:OezV8dFVj6u9+JR0Z1HQy1ebWxagw89r5RIyqbGz6d8STC3cO/PQ7ppxNUkTTAbfkT+cn4iUlmW28hw498KcwF+BC27XdCKECv/8Yq0AlcRr
GLC:BBtCVzKdTwhg1gzeRxzPtkPGujHTN+cww2jtS3U=
GLC:Y2JKXW6fbZFQjezoKO287qJnCpXhmkXihswpG3xtbIRjcGtX7AQ=
GLC:ZazfAgziONM0mr6qa5NNfVTQftKM05PwycGKb3iyAupDbXbjiJA0eneVLwzOxI25t7W/9iGTklU=
GLC:q34nh3YPe7tRQuOimUu5aBswRwPjZqhVP0hPQZXBFJ6DNlXm3MOXXSHtgSwtOrK4AA==
GLC:i4xYoIYNqCRtwQNBmTiAZOSHJq1CcLu2OWVC6xB9jLCMFfaCXFbRInoc2KuCcBle+Hm/DBisqdqPz9Jg3CHfR6zT
GLC:0d03h15gYtNurTKExCnBegNNC+rL8KCO4ogleYusnVwJAIjO0qSTPQgx+ycWGhkulds=
GLC:bywJaWeu2vH5DhSt8u0zgcvG1vlGecGPpH9ahm5XJTx/66Mgf8RCLyDwoiD26L/vS5SOuAiRluhO3yGLFfzlsLR7
GLC:APcmaUHM56nSIF7eqBFUloKfo7j9+efGD7PBJj71Wt994HdkxWAuwTIZSEOQpXbaQsMR/BD0/Q==
GLC:Zi2u5U5F8pBOfo+B2M5VRl1Ei7KgbwKqCry2tjbUJ/Z09CXv+JNkSWdFsWW3ECOKZsTRH/3hSw7xuiTdoqhqwOFY7Sm6o1WreS+E3Qvd
GLC:BBtCVzKdTwhg1gzeRxzPtkPGujHTN+cww2jtS3U=
GLC:0lQuLB4JBbc8nF3lFkecje/EqxhBxz60GG1EM3d1rhk4vaB8RDY=
GLC:bJ1EvRssLCaVkTb++zjAqn5MLaFqeus8RKp/CuDktsIrqW7gi01y/6A4RGOkNfFFPYl+Yw==
GLC:IyjwGLwbqRfjbKFebTZvCWCO03mzGCrc2TN3Hs4qHEBetzay7IW5PwUOMzaFILum+fIZ2Ou+ANM=
GLC:2fbCX3RI8wdNUqUkDbtGgV/2JFrIPf0IJHZVq+FHa3zEwnNa2pN4yB9QNrq09nSvUKYMGwAtDt9YAZAbfdUIBntrm6yYE1plv4uk+tPcyK2mg7FOvNTY5Q/2vA==
GLC:l2FuEsFT9aTC+ogFQ7kVKKLy4maPCQ5GFCdz3/ZKVO/kGfDANCpB7dDJLMRojEz5ceZ92dCAqGcVLTZ3ekkL5g==
GLC:qJrsrXsFhHP2b7g+fjYNvyQMbLTT5svkcG7A8jh9lgr1XCE0IFw0Ahz7AloYh9vi9SjfgBD/QGWcigSPjqJF6wDRoJ9GcHvhvWCaLvJ1dH7Mve12gEcHGmTh6bAe
GLC:xT1esn6sO2SI8aL7eFFHKBTptyiEHqWh5093GlUJu/ITMRLy9BoBFnTrGrwwuh0CGQvV+zNsy0lUXpI=
GLC:Nis08+ituEgCWdpN7G6NYB48XJWnwxJGKryY85SsBuWX7OIUEl7LAyly9Fu5USPCBiE8lhmsPLz9jrHix0JavVCHLn9DeTLlsJD0PjJZ3YIedDByj7clBWR4wZwbUF2lsPd+uyfVyz8NESA47A==
GLC:BBtCVzKdTwhg1gzeRxzPtkPGujHTN+cww2jtS3U=
GLC:QxuZMhfl2Tgljrm6/xnbb9SLkDVRK1O5aIPAdWVqPv6SNHNCo00=
GLC:hH91KRSdeC9h9Sea/DU0Hjpt9qsV2nzMgmF54xh1BP0S9tBt035YchbLJ+pmBw==
GLC:3kemSwVmzIes7QPtayuTVwzcjRFjzlMH3PT3JDJbUxKCW9s5gd0Yk55/RjOFVNY=
GLC:oBtYNzUdK2UCk/XsL8j3QTmZTu1i6XyIh3lBhoeGH5V64MPdK/DhI+/yO+/uVeQKKJNjQYpuDw==
GLC:PZBno7RAHyMjNsvdrwzpexpgcTf32TGiABYABRxlTPHBy5HUvUjF9h3w/Vmv7duu
GLC:8VPepsiYze4l/0JbvluCOjdQnkOkGKrzXaohftg/co97dDn3YJuNJBa+/wp49w7m7bQy3V2Ye90=
GLC:lFIJAV5T18DxPQsDXo6Vp77jZBsUEVHqH5im1gxkOOT1ZHUitdF7ip+Wod3KPypj500fIQ==
GLC:HLvhawmwbz8422nGEmQRodnwbZYJiDvDd161otQaVpYK93ad0H9r/H+kOJ7hE/O7qWc/hq+ANkJ2JrDG0QPhSfs8qx2K
GLC:BBtCVzKdTwhg1gzeRxzPtkPGujHTN+cww2jtS3U=
GLC:NX0Sf52nRPseVpHnd3Ko3O5+bHFvOUxIm4YVR3HdKA+aPjVjI24=
GLC:8EnkIwTfpMGNoGrktV1Yc3CKbTjVmIEEx1caf0DQvk4BBIZHG2QRRUnOxIfBl6tV1oU=
GLC:Jlp20nL7h+0VfkqMRVKowY8AHIdBRjCcSLeCC6vYLXEbSBcu7SaLcoP1Rdy2
GLC:i7/C5ggAA6tsNKKqFUMQG1oJNLQ1I3oo2LcnJgIYHh1LLP4yqYUaFh3UQEBuintOTX2bmMgDwcfqaUUvGOQSo9etyt9hcA==
GLC:pz++E8UTE+ANedV2jyDIZcOWb+ucY2dJISY7RUGt48+v/hUgqg8Iiaom86CK22qkSk4=
GLC:bywJaWeu2vH5DhSt8u0zgcvG1vlGecGPpH9ahm5XJTx/66Mgf8RCLyDwoiD26L/vS5SOuAiRluhO3yGLFfzlsLR7
GLC:kLg0wTn73fISbso8edO4YxqLY0r31yWsgin4Gmz0ZmW9WiOLKy1r5F6ZWz7zy7VNl+ZLsNS0/c/lxw==
GLC:pT5lKAh7YdFQOtOLFAvAHgUTGWPL/SnbdZv8lrhv49QlelBojjU6vlkf8oYW+HdIR8AxwvTVk6+nNmvUYzGNnio5BOj9/7YYF/egKn0=
