GLC:EI3iOtF/oBNF5qf5wOkQQxSOgCu558ZsAPvNoiKgZcHsxp6hjglOv2hNQg==
GLC:8yfAktWV90jt6LxlZcnK7/dEPByBeWw4Za47zmYYKxQ0rBB6NaeDg8rGiQ8niA==
GLC:twrJIc0USxRvt5OPNqbusaUU/fDFanceASR+q9xjrp94LI17As4rPUMfwPTokaEV
GLC:/0CzY9JWG85lLtg15CyWWL+sGO4BQ8a15tMjSea/2zF0hMYGte+eC0dJf2ogoeGuzDAbrLv0LQ==
GLC:BBtCVzKdTwhg1gzeRxzPtkPGujHTN+cww2jtS3U=
GLC:mgiePvNz3R+AiLi2buCrvkc4fuj+X2AYCyGGcmD4FfSgldR/v9uxHKfd
GLC:5wH4MO/yPskpbxI0uDGN1iRedGqBkYjecOKm8gWGFVLhgCivELdC//uoc04QBYHgjVgKNg5H9ykq20BD+JGuG00byLRxfN0DQnSdj1bMjt4=
GLC:kfr/Jh1UCUYJuY7c1+7MX9RCbSNFfAZ86Oe1CO51ProEk93gCiB2Tf4pXBbL/06zNcxx8su2aik=
GLC:KQiVeh+MrfwgQaPVzyp1GhxZAatkS35+7JWfeqm87tL5QX07T+y9zDNVdHUKnC3ijfiwVfwO386jL5P0kuKoUvFR
GLC:IlOh2/ojTFIK5r7xtiRa7MNCJv2C9SIiXfyJkfTijMvxyzMFdlN7/EbNMeWN0m0hrsoRvg4=
GLC:BBtCVzKdTwhg1gzeRxzPtkPGujHTN+cww2jtS3U=
GLC:i+KCtlFoEETmZvp8Xf17HlLZzTmZXVAWptnYgYr7+Xd8GyA9PSiYzg==
GLC:5/NDhbfEkFwWfG87vbsHMIMeaa1FPDXA02nk7DoZcq7Ju7pSN+SoH5n5GvjC
GLC:quhvRSBWDRDIBnkJHSNgO/JfxGe3qwd4AKbjjzaKUJjNAVKIObtEF9Js6Z5wPgGQJWTNCnWAGoiZsKg=
GLC:8eUHG/RThXYtSmvLgm9QnhtZNctKP2n8k148QzIzPP/q6O7fe538ypNKwMA=
GLC:BBtCVzKdTwhg1gzeRxzPtkPGujHTN+cww2jtS3U=
GLC:b3H3SJBRDtw8P+EJn6mx6LirjqkZUNd6WC04tomJAvO0oBCl2HIBoPM=
GLC:EI3iOtF/oBNF5qf5wOkQQxSOgCu558ZsAPvNoiKgZcHsxp6hjglOv2hNQg==
